apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntjobrecommender

spec:
  replicas: 3
  selector:
    matchLabels:
      app: ntjobrecommender
  template:
    metadata:
      labels:
        app: ntjobrecommender

    spec:
      containers:
        - name: web
          image: nt-job-recommender:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP